#### SEIS 763-01: Homework 1
##### Completed by: Jamie Boehme

1. Read in the CSV file “ML_HW_Data_FisherIris.csv” into a matrix named as
“Iris”. Please do NOT output the whole matrix in our answer.

In [1]:
import pandas as pd
import numpy as np


file = 'https://raw.githubusercontent.com/jamieboehme/Machine-Learning/main/ML_HW_Data_FisherIris.csv'
df = pd.read_csv(file, header= None)
Iris = df.to_numpy()
print('Below is a partial printout of the Iris matrix')
print(Iris[0:10])

Below is a partial printout of the Iris matrix
[[ 2 14 33 50  0]
 [24 56 31 67  1]
 [23 51 31 69  1]
 [ 2 10 36 46  0]
 [20 52 30 65  1]
 [19 51 27 58  1]
 [13 45 28 57  2]
 [16 47 33 63  2]
 [17 45 25 49  1]
 [14 47 32 70  2]]


2. Display total number of rows and total number of columns of the matrix “Iris”.

In [2]:
print('The total number of rows and columns in matrix Iris respectively are:')
Iris.shape

The total number of rows and columns in matrix Iris respectively are:


(150, 5)

3. Display all the row numbers (i.e. record numbers) that have the 5th column less
than 0.

In [3]:
np.where(np.any(Iris[:,4:]<0, axis=1))

(array([ 10,  23,  58,  89, 108, 136]),)

4. Remove the rows with the 5th column less than 0 from the “Iris” matrix. Please do
NOT output the whole resulting matrix in our answer.

In [4]:
Iris = np.delete(Iris,(10,23,58,89,108,136),0)

5. Display total number of rows and total number of columns of the “Iris” matrix
again.

In [5]:
print('The total number of rows and columns in matrix Iris after deletion of records in the fifth column that have values less than 0, respectively are:')
Iris.shape

The total number of rows and columns in matrix Iris after deletion of records in the fifth column that have values less than 0, respectively are:


(144, 5)

6. Copy the first 4 columns in the new “Iris” matrix into a new matrix “X”. Please
do NOT output the whole resulting matrix in our answer.

In [6]:
X = np.array(Iris[:,0:4])
print('Below is a partial print out of variable X:')
print(X[0:10])

Below is a partial print out of variable X:
[[ 2 14 33 50]
 [24 56 31 67]
 [23 51 31 69]
 [ 2 10 36 46]
 [20 52 30 65]
 [19 51 27 58]
 [13 45 28 57]
 [16 47 33 63]
 [17 45 25 49]
 [14 47 32 70]]


7. Copy the 5th columns in the new “Iris” matrix into a new variable (or matrix) “Y”.
Please do NOT output the whole resulting matrix in our answer.

In [7]:
Y = np.array(Iris[:,4:])
print('Below is a partial print out of variable Y:')
print(Y[0:10])

Below is a partial print out of variable Y:
[[0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [2]
 [2]
 [1]
 [2]]


8. Display the maximum value and the minimum value of EACH column in “X”.

In [8]:
max_values = X.max(axis=0)
min_values = X.min(axis=0)
print('The maximum values in column X respectively are:', max_values)
print('The minimum values in column X respectively are:', min_values)

The maximum values in column X respectively are: [25 69 44 79]
The minimum values in column X respectively are: [ 1 10 20 43]


9. Display total number of elements (i.e. items) in the third column of the matrix
“X” that are greater than 36.

In [9]:
cond_X = np.where(np.any(X[:,2:3]>36, axis=1))
elements = np.asarray(cond_X).size
print('There are',elements, 'total elements in the third column of the matrix "X" that have a value greater than 36')

There are 15 total elements in the third column of the matrix "X" that have a value greater than 36
